-- no-transaction
-- -------------------------------------------------------------------------
-- Structural close-out of today's TRUST-consumer/`trust_event_backlog_match`
-- CRS+time mismatching incident (2026-09-25): two `trains` rows ended up
-- sharing one real-world train's TRUST `train_id` for the same
-- `service_date`, so a London Northwestern Euston->Birmingham subscription
-- showed an unrelated Avanti Euston->Liverpool service's movements. Both
-- write paths that could cause this have already been patched with an
-- application-level veto (`is_provable_identity_contradiction`, this
-- module and its equivalent in `crates/trust-consumer/src/matching.rs`) --
-- this migration is the schema-level backstop behind those guards, so this
-- whole bug class becomes structurally impossible, not merely guarded
-- against by application code that a future change could regress.
--
-- Confirmed safe against every current write path before adding this:
--
-- * `trains.train_id` (TRUST's own daily identifier) is nullable by design
--   (`20260906100000_trains.sql`) -- a schedule-matched-but-not-yet-live-
--   resolved row has no `train_id` at all. Postgres treats every NULL as
--   distinct from every other NULL for uniqueness purposes, so a bare
--   `UNIQUE (train_id, service_date)` would already let any number of
--   still-pending rows coexist for one `service_date` -- but this codebase's
--   own established convention for exactly this shape (see
--   `tracked_trains_resolved_identity` in the now-retired
--   `20260828120000_train_tracking.sql`, and
--   `train_movement_events_trains_id_dedup` /
--   `train_current_state_trains_id` in `20260906110000_train_movement_trains_id.sql`)
--   is an explicit partial index, `WHERE train_id IS NOT NULL`, so the
--   NULL-skipping behavior reads as documented intent rather than an
--   incidental side effect a future reader has to rediscover from Postgres
--   semantics. Matched here for the same reason.
--
-- * Two different subscriptions sharing one physical train is already
--   modeled as ONE `trains` row referenced by multiple
--   `train_subscriptions.trains_id` foreign keys -- never as two `trains`
--   rows for the same identity (`docs/superpowers/specs/2026-09-06-shared-train-identity-design.md`).
--   `find_or_create_train`/`find_or_create_trains_batch`/
--   `find_or_create_train_with_schedule_match` (`crates/api/src/data/trains.rs`)
--   are the only write paths that ever create a `trains` row, and every one
--   of them upserts via `ON CONFLICT (train_uid, service_date) DO UPDATE
--   ... RETURNING id` -- idempotent by construction, so no code path in
--   this codebase creates a second row for an identity that already has
--   one. `mark_train_resolved`/`mark_trains_resolved_batch` (the only
--   writers of `train_id` itself) always target an existing row's `id`,
--   never insert a new one. So no legitimate write pattern here ever needs
--   two `trains` rows to carry the same `(train_id, service_date)` pair.
--
-- * UPDATE (this migration's own revision, superseding the framing this
--   comment originally had): rather than leaving existing corrupted data
--   for a human to discover only when this file's `CREATE UNIQUE INDEX
--   CONCURRENTLY` fails at deploy time, the immediately-preceding
--   migration, `20260925221500_close_out_trains_train_id_service_date_collisions.sql`,
--   now closes out every `(train_id, service_date)` collision first --
--   deleting both/all sides of every colliding group outright, after
--   detaching (never deleting) any `train_subscriptions` row that pointed
--   at one of them. See that file's own header comment for the full
--   reasoning (why it deletes rather than repairs in place, exactly how a
--   detached subscription's `resolution_status` is recomputed, and the
--   full FK fan-out audit).
--
--   That cleanup is a SEPARATE migration file, deliberately -- not folded
--   into this one, even though this one's own header used to say "this
--   migration alone doesn't touch existing corrupted data" as if a single
--   file could do both. It cannot: sqlx sends an entire migration file to
--   Postgres as ONE simple-query protocol message (verified empirically
--   against Postgres 18 while writing this), and Postgres refuses to run
--   `CREATE INDEX CONCURRENTLY` at all when it is not the ONLY statement in
--   such a message -- not merely when it is inside an explicit `BEGIN`
--   block. `-- no-transaction` (which this file still opts into, below)
--   only removes sqlx's OWN wrapping transaction; it cannot make Postgres
--   treat a multi-statement message as anything other than one batch for
--   this purpose, no matter how the statements inside it are ordered or
--   bracketed with `BEGIN`/`COMMIT`. (`20260906110000_train_movement_trains_id.sql`'s
--   own doc comment already names this same shape of problem -- "this one
--   also mixes DDL with a data backfill, so it genuinely wants its own
--   transaction; splitting it would have needed more than a CONCURRENTLY
--   rewrite" -- for exactly this reason.) Two migration files, applied in
--   the ascending version order sqlx already guarantees, is the only way
--   to get an ordinary transactional data cleanup to run immediately
--   before an index build that must remain the sole statement in its own
--   file. This file's own content is otherwise UNCHANGED from before that
--   split -- still exactly one statement.
--
-- * The one already-known real corrupted row from today's incident
--   (`trains.id = 6095140`, `train_uid = 'Y80926'`, `service_date =
--   '2026-09-25'`) is now handled by the preceding migration like any
--   other collision -- it no longer needs to be left for this file's
--   `CREATE UNIQUE INDEX CONCURRENTLY` to discover the hard way. The
--   standalone `scripts/remediate-2026-09-25-cross-matched-trains-row.sql`
--   script (which fixes that one row in place, preserving its schedule
--   match rather than deleting it) is therefore superseded for that
--   incident -- it is kept in the repo as a historical record of the
--   incident and as a worked example of the narrower "TRUST Activation
--   contradicts identity" signature, not because it still needs to be run.
--   If somehow run before these migrations deploy, it is harmless and
--   simply leaves nothing for the preceding migration's own cleanup to
--   find for that one row.
--
-- * Whether a real duplicate-key violation could still reach this file's
--   `CREATE UNIQUE INDEX CONCURRENTLY` after the preceding migration's
--   cleanup is, as far as this migration can determine, no -- that
--   migration deletes every row involved in any `(train_id, service_date)`
--   collision, which is exactly the condition this unique index would
--   otherwise reject. `CREATE UNIQUE INDEX CONCURRENTLY` never runs inside
--   a transaction (Postgres rejects that combination outright), so IF
--   something unforeseen still collides (e.g. a live write racing this
--   migration), the failure mode is unchanged from before: an INVALID
--   index left behind for a human to `DROP INDEX` and retry, rather than
--   the ACCESS-EXCLUSIVE-lock-timeout flavor of startup crash-loop
--   `crates/api/tests/migration_index_locking.rs` exists to prevent
--   (`main.rs` runs migrations before binding its listener, so any
--   transaction-wrapped index build blocks `/public/health` for its whole
--   duration). Either way, the failure mode is a clean, retriable migration
--   step, never a stuck lock or a corrupted transaction.
-- -------------------------------------------------------------------------

CREATE UNIQUE INDEX CONCURRENTLY trains_train_id_service_date
    ON trains (train_id, service_date)
    WHERE train_id IS NOT NULL;
