'use client';

import { useId } from 'react';
import { Badge, Tooltip, VisuallyHidden } from '@mantine/core';

/** Note for anything the incident enricher (`crates/enricher`, a
 * self-hosted LLM) shaped: severity escalation or demotion, the "expected
 * to end by" annotations appended to a status reason, and `impactType`. */
export const ENRICHED_INCIDENT_NOTE =
  'Severity, timing and impact are partly worked out by an AI model reading the National Rail message, and may be inaccurate. Check the original message.';

/** Shorter form for badges inside repeated rows and cards, where the note
 * also becomes part of the enclosing control's accessible name. */
export const ENRICHED_INCIDENT_SHORT_NOTE =
  'Status partly worked out by AI from the National Rail message; may be inaccurate.';

/** Note for the chat's answers. */
export const CHAT_AI_NOTE =
  "Answers are generated by Anthropic's Claude using your own API key, and may be inaccurate. Check with the train operator before travelling.";

/** A small "AI" marker for LLM-derived content (UK legal audit LEG-16).
 *
 * Accessibility: the badge is not focusable, because it sits inside
 * interactive elements (the `IssueList` accordion button, the linked
 * `LineStatusCard`), where a focusable child would break axe's
 * `nested-interactive` rule. So the note is not only in the hover tooltip:
 * it is also in visually hidden text right after the badge, which screen
 * readers read in order (including as part of an enclosing button's name),
 * and the badge points at it with `aria-describedby`. */
/** The one label every AI marker uses. */
export const AI_BADGE_LABEL = 'AI summary';

export function AiGeneratedBadge({ note }: { note: string }) {
  const noteId = useId();
  return (
    <>
      <Tooltip label={note} multiline w={280} events={{ hover: true, focus: true, touch: true }}>
        <Badge data-ai-badge variant="outline" color="gray" size="sm" tt="none" aria-describedby={noteId}>
          {AI_BADGE_LABEL}
        </Badge>
      </Tooltip>
      <VisuallyHidden id={noteId}>{note}</VisuallyHidden>
    </>
  );
}

/** True when a status came from a Knowledgebase incident, which is the only
 * source the enricher processes (`crates/aggregator/src/aggregation.rs`,
 * `status_from_incident`). The API doesn't say whether the extraction
 * actually changed this status, so this marks every status it *may* have
 * shaped. */
export function isEnricherInfluenced(source: string | null | undefined): boolean {
  return !!source && source.startsWith('knowledgebase-incident-');
}
