# syntax=docker/dockerfile:1@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32
# Multi-stage build for the `schedule-reference` service. See
# docker/schedule-ingest.Dockerfile's own header comment for the full
# rationale behind the rust:1.88-bookworm pin --
# unchanged here, this crate shares the same `common`-crate-driven
# reqwest -> url -> idna -> icu_* transitive dependency chain.
#
# Build from the repo root:
#   docker build -f docker/schedule-reference.Dockerfile .
# BEGIN generated by scripts/gen-rust-dockerfiles.py; edit it, not this
# Builder stages: cargo-chef, so the dependency build is a layer of its own
# that a source-only change reuses (locally, and in CI from the registry
# build cache, see .github/workflows/containers.yml). The generator's
# docstring explains the stages and why the cook and the build must take
# exactly the same flags.
#
# CARGO_PROFILE picks the cargo build profile (and matching target/<profile>
# output dir): "release" (default) for optimized builds, "debug" for fast
# unoptimized dev builds. Set to "debug" by docker-compose.dev.yml, the
# override that `dev.env` selects via COMPOSE_FILE; docker-compose.yml on
# its own leaves it at "release".
ARG CARGO_PROFILE=release

FROM rust:1.88-bookworm@sha256:af306cfa71d987911a781c37b59d7d67d934f49684058f96cf72079c3626bfe0 AS chef

# The registry and git caches hold only downloaded sources, so every
# service shares them. `sharing=locked`: docker-compose builds in parallel.
# hadolint ignore=DL3008 # apt versions unpinned on purpose; see .hadolint.yaml
RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git,sharing=locked \
    apt-get update \
    && apt-get install -y --no-install-recommends cmake libcurl4-openssl-dev libsasl2-dev libssl-dev pkg-config \
    && rm -rf /var/lib/apt/lists/* \
    && cargo install cargo-chef --locked --version 0.1.78

WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
ARG CARGO_PROFILE

# No cache mount on target/: the cooked dependencies must land in this
# layer, which is what the next build (and CI's registry cache) reuses.
COPY --from=planner /app/recipe.json recipe.json
RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git,sharing=locked \
    if [ "${CARGO_PROFILE}" = "release" ]; then \
      cargo chef cook --release --locked --recipe-path recipe.json --bin schedule-reference; \
    else \
      cargo chef cook --locked --recipe-path recipe.json --bin schedule-reference; \
    fi

COPY . .
# The same flags as the cook. cargo's log is printed after the build, then
# checked: a `Compiling` line without an /app path is a dependency the cook
# should have built, so the cook no longer matches and the build fails. The
# binaries are copied out and target/ is deleted in the same RUN, so this
# layer stays small in the build cache.
RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git,sharing=locked \
    if [ "${CARGO_PROFILE}" = "release" ]; then \
      cargo build --release --locked --bin schedule-reference > /tmp/cargo-build.log 2>&1; \
    else \
      cargo build --locked --bin schedule-reference > /tmp/cargo-build.log 2>&1; \
    fi; \
    status=$?; \
    cat /tmp/cargo-build.log; \
    if [ "${status}" -ne 0 ]; then exit "${status}"; fi; \
    if ! awk '/^ +Compiling / && !/ \(\/app\// { print; found = 1 } END { exit found }' /tmp/cargo-build.log; then \
      echo "error: the build compiled the dependencies above; the cargo chef cook flags no longer match the build's" >&2; \
      exit 1; \
    fi; \
    cp "/app/target/${CARGO_PROFILE}/schedule-reference" /usr/local/bin/schedule-reference \
    && rm -rf /app/target /tmp/cargo-build.log
# END generated by scripts/gen-rust-dockerfiles.py

FROM debian:bookworm-slim@sha256:3783cc01769c7b2b1b83a5c5ad96c815348e28ed7da68e2e3687004faa906251

# tini as PID 1 (signal forwarding, zombie reaping): see
# docker/api.Dockerfile's runtime stage for why, and for the version pin.
ARG TINI_VERSION=0.19.0-1

# hadolint ignore=DL3008 # apt versions unpinned on purpose; see .hadolint.yaml
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates "tini=${TINI_VERSION}*" \
    && rm -rf /var/lib/apt/lists/* \
    && tini --version \
    && groupadd --system --gid 1000 poller \
    && useradd --system --no-create-home --shell /usr/sbin/nologin --uid 1000 --gid 1000 poller

COPY --from=builder /usr/local/bin/schedule-reference /usr/local/bin/schedule-reference
# Task 7's second responsibility (per-line CIF SCHEDULE population publish)
# reads the same static line catalogue `aggregator`/`api` already bake in
# the same way (see those Dockerfiles' own identical COPY step) -- this
# crate had no use for `lines/` before Task 7.
COPY --chown=poller:poller lines/ /app/lines/

# Numeric USER, not the `poller` name useradd created above: Kubernetes'
# runAsNonRoot admission check (this chart's podSecurityContext sets
# runAsNonRoot: true with no explicit runAsUser) resolves the image's
# config purely from its manifest -- it does NOT read /etc/passwd inside
# the image -- so a symbolic USER fails admission with "container has
# runAsNonRoot and image has non-numeric user, cannot verify user is
# non-root". Pinned to the same uid/gid useradd was given above so this
# stays in sync with the group ownership set via COPY --chown/groupadd.
USER 1000:1000

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/schedule-reference"]
