# syntax=docker/dockerfile:1@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32
# Multi-stage build for the `schedule-ingest` service.
#
# Builder pin: matches poller-incidents/poller-stations/poller-tfl/poller-tocs/
# poller-ldbws at rust:1.88-bookworm — this crate pulls in the same reqwest ->
# url -> idna -> idna_adapter -> icu_normalizer/icu_provider transitive chain
# (through the `common` crate every service in this workspace depends on)
# requiring rustc 1.88+ -- confirmed by actually building poller-ldbws's image
# against rust:1.86-bookworm first and hitting:
#   "error: rustc 1.86.0 is not supported ... icu_provider@2.3.1 requires
#   rustc 1.88"
#
# Build from the repo root so the workspace's Cargo.toml/Cargo.lock and
# crates/common path dependency are all in the build context:
#   docker build -f docker/schedule-ingest.Dockerfile .
# BEGIN generated by scripts/gen-rust-dockerfiles.py; edit it, not this
# Builder stages: cargo-chef, so the dependency build is a layer of its own
# that a source-only change reuses (locally, and in CI from the registry
# build cache, see .github/workflows/containers.yml). The generator's
# docstring explains the stages and why the cook and the build must take
# exactly the same flags.
#
# CARGO_PROFILE picks the cargo build profile (and matching target/<profile>
# output dir): "release" (default) for optimized builds, "debug" for fast
# unoptimized dev builds. Set to "debug" by docker-compose.dev.yml, the
# override that `dev.env` selects via COMPOSE_FILE; docker-compose.yml on
# its own leaves it at "release".
ARG CARGO_PROFILE=release

FROM rust:1.88-bookworm@sha256:af306cfa71d987911a781c37b59d7d67d934f49684058f96cf72079c3626bfe0 AS chef

# The registry and git caches hold only downloaded sources, so every
# service shares them. `sharing=locked`: docker-compose builds in parallel.
# hadolint ignore=DL3008 # apt versions unpinned on purpose; see .hadolint.yaml
RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git,sharing=locked \
    apt-get update \
    && apt-get install -y --no-install-recommends cmake libcurl4-openssl-dev libsasl2-dev libssl-dev pkg-config \
    && rm -rf /var/lib/apt/lists/* \
    && cargo install cargo-chef --locked --version 0.1.78

WORKDIR /app

FROM chef AS planner
# `.` is the build context as this Dockerfile's .dockerignore allowlist
# leaves it: the workspace and the data files it embeds or ships, not the
# whole repo (see the generator's docstring, "Build inputs").
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
ARG CARGO_PROFILE

# No cache mount on target/: the cooked dependencies must land in this
# layer, which is what the next build (and CI's registry cache) reuses.
COPY --from=planner /app/recipe.json recipe.json
RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git,sharing=locked \
    if [ "${CARGO_PROFILE}" = "release" ]; then \
      cargo chef cook --release --locked --recipe-path recipe.json --bin schedule-ingest; \
    else \
      cargo chef cook --locked --recipe-path recipe.json --bin schedule-ingest; \
    fi

COPY . .
# The same flags as the cook. cargo's log is printed after the build, then
# checked: a `Compiling` line without an /app path is a dependency the cook
# should have built, so the cook no longer matches and the build fails. The
# binaries are copied out and target/ is deleted in the same RUN, so this
# layer stays small in the build cache.
RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git,sharing=locked \
    if [ "${CARGO_PROFILE}" = "release" ]; then \
      cargo build --release --locked --bin schedule-ingest > /tmp/cargo-build.log 2>&1; \
    else \
      cargo build --locked --bin schedule-ingest > /tmp/cargo-build.log 2>&1; \
    fi; \
    status=$?; \
    cat /tmp/cargo-build.log; \
    if [ "${status}" -ne 0 ]; then exit "${status}"; fi; \
    if ! awk '/^ +Compiling / && !/ \(\/app\// { print; found = 1 } END { exit found }' /tmp/cargo-build.log; then \
      echo "error: the build compiled the dependencies above; the cargo chef cook flags no longer match the build's" >&2; \
      exit 1; \
    fi; \
    cp "/app/target/${CARGO_PROFILE}/schedule-ingest" /usr/local/bin/schedule-ingest \
    && rm -rf /app/target /tmp/cargo-build.log
# END generated by scripts/gen-rust-dockerfiles.py

FROM debian:bookworm-slim@sha256:3783cc01769c7b2b1b83a5c5ad96c815348e28ed7da68e2e3687004faa906251

# tini as PID 1 (signal forwarding, zombie reaping): see
# docker/api.Dockerfile's runtime stage for why, and for the version pin.
ARG TINI_VERSION=0.19.0-1

# reqwest's native-tls backend verifies certs against the system store, so
# the runtime image needs a CA bundle even though it otherwise only carries
# the one binary.
# hadolint ignore=DL3008 # apt versions unpinned on purpose; see .hadolint.yaml
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates "tini=${TINI_VERSION}*" \
    && rm -rf /var/lib/apt/lists/* \
    && tini --version \
    && groupadd --system --gid 1001 poller \
    && useradd --system --no-create-home --shell /usr/sbin/nologin --uid 1001 --gid 1001 poller

COPY --from=builder /usr/local/bin/schedule-ingest /usr/local/bin/schedule-ingest

# Numeric USER, not `poller`: Kubernetes' runAsNonRoot admission check
# (this chart's podSecurityContext sets runAsNonRoot: true with no
# explicit runAsUser) resolves the image's config purely from its
# manifest -- it does NOT read /etc/passwd inside the image -- so a
# symbolic USER fails admission with "container has runAsNonRoot and
# image has non-numeric user, cannot verify user is non-root". Pinned to
# 1001, deliberately NOT 1000: this container shares
# scheduleFeed's PVC with the `sftp` container, whose drakkan/sftpgo
# image runs as a fixed non-root USER 1000:1000 of its own -- see
# docker-compose.yml's schedule-feed-volume-permissions comment and the
# chart's scheduleFeed.podSecurityContext (fsGroup: 1000), both of which
# rely on `ingest` reaching the shared volume via the 1000 *group*
# (fsGroup/group_add), not by being uid 1000 itself. Keeping this uid off
# 1000 keeps that separation intact.
USER 1001:1001

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/schedule-ingest"]
