import { List, ListItem, Text } from '@mantine/core';
import type { Metadata } from 'next';
import { ContactEmail, LegalPage, LegalSection, requireLegalPages } from '@/components/LegalPage';
import { NON_AFFILIATION_STATEMENT } from '@/components/OpenDataAttribution';
import { TextLink } from '@/components/TextLink';
import { LEGAL_CONFIG, legalPageMetadata } from '@/lib/legal';
import { withAbsoluteTitle } from '@/lib/pageMetadata';

// ============================================================================
// DRAFT -- NOT LEGAL ADVICE -- REVIEW BEFORE PUBLISHING.
// Drafted from the 2026-09-27 UK legal compliance gap analysis (LEG-12,
// LEG-13, LEG-14, LEG-25 and "Documents the operator needs" item 3). The
// operator, and ideally a lawyer, must review it before setting
// LEGAL_PAGES_PUBLISHED. In particular: the liability clause must stay fair
// under the Consumer Rights Act 2015 (it must not exclude liability for
// death, personal injury or negligence), and the Online Safety Act 2023
// section must match the operator's actual reporting and complaints process
// and the illegal-content risk assessment.
// ============================================================================

// Reads the legal-pages flags per request (see lib/legal.ts).
export const dynamic = 'force-dynamic';

export function generateMetadata(): Metadata {
  return withAbsoluteTitle(legalPageMetadata('Terms of use', 'The terms for using Distant Signal.'));
}

export default function TermsPage() {
  const mode = requireLegalPages();
  const { OPERATOR_NAME, MINIMUM_AGE } = LEGAL_CONFIG;
  return (
    <LegalPage draft={mode === 'preview'} title="Terms of use">
      <LegalSection title="About these terms">
        <Text>
          Distant Signal is a free rail information service run by {OPERATOR_NAME} (&quot;we&quot;). By using it, or by
          signing in, you agree to these terms. Our{' '}
          <TextLink href="/privacy" underline="always" inline>
            privacy notice
          </TextLink>{' '}
          explains how we handle your personal data. Contact us at <ContactEmail />.
        </Text>
      </LegalSection>

      <LegalSection title="Who can use it">
        <Text>You must be at least {MINIMUM_AGE} to create an account.</Text>
      </LegalSection>

      <LegalSection title="Not an official service">
        <Text>{NON_AFFILIATION_STATEMENT}</Text>
      </LegalSection>

      <LegalSection title="Rail information is provided as is">
        <Text>
          Our information comes from public data feeds (see{' '}
          <TextLink href="/attribution" underline="always" inline>
            data sources
          </TextLink>
          ). It is provided &quot;as is&quot; and can be late, incomplete or wrong. Some incident timing and severity is
          worked out by an AI model and is marked as AI. Always check with the train operator or National Rail before
          you travel.
        </Text>
        <Text>
          Delay Repay estimates are a guide, not advice or a guarantee. We never submit claims for you. The train
          operator decides every claim using its own records, which can differ from ours.
        </Text>
      </LegalSection>

      <LegalSection title="The AI chat">
        <Text>
          The chat uses your own Anthropic API key and account, and Anthropic&apos;s terms apply to that use. Its
          answers are generated by AI and may be inaccurate. Do not rely on them without checking.
        </Text>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <Text>You must not:</Text>
        <List size="sm" spacing={4}>
          <ListItem>
            put illegal, abusive, hateful or harassing content in anything other people can see, such as group names,
            names of trains, journeys and custom lines, or your display name;
          </ListItem>
          <ListItem>
            use share or invite links to harass people, or share them with people you know will misuse them;
          </ListItem>
          <ListItem>
            scrape the site or its API, or send automated requests in volumes that affect other users;
          </ListItem>
          <ListItem>try to get into accounts or data that are not yours, or disrupt the service.</ListItem>
        </List>
      </LegalSection>

      <LegalSection title="Reporting content and complaints">
        <Text>
          If you see content on Distant Signal that you think is illegal or breaks these terms, report it to{' '}
          <ContactEmail />. Tell us where it is (for example the group or share link) and what the problem is. We review
          every report, remove illegal content as soon as we become aware of it, and may suspend the account
          responsible.
        </Text>
        <Text>
          You can also use the same address to complain about how we handled a report, about content we removed, or
          about action we took against your account. We will reply and tell you what we decided and why.
        </Text>
        <Text>
          More ways to contact us are on the{' '}
          <TextLink href="/contact" underline="always" inline>
            contact page
          </TextLink>
          .
        </Text>
      </LegalSection>

      <LegalSection title="Suspension and ending your account">
        <Text>
          We may suspend or close an account that breaks these terms, and may change or stop the service. You can delete
          your account at any time from your account page.
        </Text>
      </LegalSection>

      <LegalSection title="Our liability">
        <Text>
          The service is free, and we are not responsible for travel decisions you make using it, including missed
          connections, extra travel costs or unsuccessful Delay Repay claims. Nothing in these terms limits our
          liability for death or personal injury caused by our negligence, for fraud, or for anything else the law does
          not allow us to limit.
        </Text>
      </LegalSection>

      <LegalSection title="Law">
        <Text>
          These terms are governed by the law of England and Wales. If you live elsewhere in the UK, you can also bring
          a claim in the courts where you live.
        </Text>
      </LegalSection>
    </LegalPage>
  );
}
