// The Next.js build ID (next.config.mjs's `generateBuildId`), derived from
// the frontend's inputs instead of Next's default random string.
//
// Why: scripts/stamp-sw-version.mjs stamps the build ID into public/sw.js,
// and the browser installs a new service worker (purging the old caches)
// whenever sw.js's bytes change. With a random ID every deploy did that,
// and every image build produced a new .next/ layer, even when nothing in
// frontend/ had changed. With this, the ID (and so sw.js, and the image
// layer) changes only when the frontend does.
//
// The ID is a SHA-256 over the sorted (path, content hash) pairs of every
// input file under frontend/: the source tree, configs, public/, the
// Dockerfile and package-lock.json (which pins every dependency). Build
// output and local-only files (EXCLUDED_* below) are left out. The file
// list comes from git when frontend/ is in a work tree (tracked plus
// untracked-but-not-ignored files, so a local uncommitted change counts),
// else from walking the directory: the Docker build has no .git. On a
// clean checkout both give the same list, so CI, the image build and a
// local build of the same tree agree. Content is hashed byte for byte;
// .gitattributes keeps LF line endings on every checkout.
//
// Node built-ins only, like stamp-sw-version.mjs.

import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';

// Directories (any depth) that are build output, dependencies or local
// test output, never inputs. node_modules is covered by package-lock.json.
const EXCLUDED_DIRS = new Set(['node_modules', '.next', '.git', 'e2e-report', 'test-results']);

/**
 * Whether a frontend-relative, `/`-separated path is a build input.
 * @param {string} rel
 */
export function isInput(rel) {
  const parts = rel.split('/');
  if (parts.some((part) => EXCLUDED_DIRS.has(part))) return false;
  const name = parts[parts.length - 1] ?? '';
  // Generated by `next build`/`next dev` itself, mid-build.
  if (rel === 'next-env.d.ts' || name.endsWith('.tsbuildinfo')) return false;
  // Local env files (frontend/Dockerfile.dockerignore leaves them out of
  // the image build too); the committed template stays an input.
  if (name === '.env' || (name.startsWith('.env.') && name !== '.env.example')) return false;
  return true;
}

/**
 * Every file under `dir`, relative and `/`-separated, or null when git
 * can't list them (no git, or not a work tree).
 * @param {string} dir
 * @returns {string[] | null}
 */
function gitFiles(dir) {
  try {
    const out = execFileSync('git', ['ls-files', '-z', '--cached', '--others', '--exclude-standard', '--', '.'], {
      cwd: dir,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    });
    return out.split('\0').filter(Boolean);
  } catch {
    return null;
  }
}

/**
 * Every file under `dir`, relative and `/`-separated, skipping excluded
 * directories without descending into them.
 * @param {string} dir
 * @param {string} [prefix]
 * @returns {string[]}
 */
function walkFiles(dir, prefix = '') {
  /** @type {string[]} */
  const files = [];
  for (const entry of readdirSync(path.join(dir, prefix), { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      if (!EXCLUDED_DIRS.has(entry.name)) files.push(...walkFiles(dir, rel));
    } else {
      files.push(rel);
    }
  }
  return files;
}

/**
 * The frontend's input files, sorted.
 * @param {string} dir the frontend directory
 * @param {{ useGit?: boolean }} [options] `useGit: false` forces the walk
 */
export function inputFiles(dir, { useGit = true } = {}) {
  const listed = (useGit ? gitFiles(dir) : null) ?? walkFiles(dir);
  // git lists index entries whose file was deleted from the work tree.
  return listed
    .filter((rel) => isInput(rel))
    .filter((rel) => {
      try {
        return statSync(path.join(dir, rel)).isFile();
      } catch {
        return false;
      }
    })
    .sort();
}

/**
 * The build ID for the frontend in `dir`: 24 hex characters of a SHA-256
 * over its input files' paths and contents.
 * @param {string} dir the frontend directory
 * @param {{ useGit?: boolean }} [options]
 */
export function computeBuildId(dir, options) {
  const hash = createHash('sha256');
  for (const rel of inputFiles(dir, options)) {
    const content = createHash('sha256')
      .update(readFileSync(path.join(dir, rel)))
      .digest('hex');
    hash.update(`${rel}\0${content}\n`);
  }
  return hash.digest('hex').slice(0, 24);
}
