//! The schema version this build needs: [`REQUIRED_MIGRATION`] (1A.12),
//! then the schema gate `wait_for_schema` (1B.2, spec §12.2).
//!
//! No caller yet: the gate in 1B.2 compares it with
//! `SELECT max(version) FROM _sqlx_migrations WHERE success`.

/// The version of the newest migration this build embeds: the largest
/// `<version>` among `crates/api/migrations/<version>_<description>.sql`
/// (`crates/ds-store/migrations` from plan task 1B.1). Generated by
/// `build.rs` at build time, so a new migration moves it with no edit here.
#[allow(
    clippy::unreadable_literal,
    reason = "generated: the version exactly as in the migration's file name"
)]
pub const REQUIRED_MIGRATION: i64 = include!(concat!(env!("OUT_DIR"), "/required_migration.rs"));

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::*;

    /// Read at test time, independently of `build.rs`: the newest file in
    /// the migrations directory, by name (versions are fixed-width
    /// timestamps, so the newest sorts last).
    #[test]
    fn required_migration_is_the_newest_migration_file() {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../api/migrations");
        let newest = std::fs::read_dir(&dir)
            .unwrap()
            .map(|entry| entry.unwrap().file_name().into_string().unwrap())
            .filter(|name| {
                Path::new(name).extension().is_some_and(|ext| ext == "sql")
                    && !name.ends_with(".down.sql")
            })
            .max()
            .unwrap();
        let version: String = newest.chars().take_while(char::is_ascii_digit).collect();
        assert_eq!(
            REQUIRED_MIGRATION.to_string(),
            version,
            "newest migration file: {newest}"
        );
    }
}
