-- GENERATED by scripts/gen-db-grants.py from db-grants.yaml (with the
-- template scripts/db-grants.sql.tpl). DO NOT EDIT: edit db-grants.yaml,
-- then run `uv run scripts/gen-db-grants.py render`.
--
-- Per-service Postgres roles (docs/postgres-app-role.md, Stage 0b; ingest
-- architecture spec §6). Idempotent. Run with psql as a SUPERUSER in the
-- application database, AFTER postgres-roles.sql (it needs the app role):
--
--   psql -X -d distant_signal -v app=distant_signal_app \
--     [-v <role>=<name>] [-v <role>_connection_limit=N] \
--     -f postgres-grants.sql
--
-- Passwords come from the environment (psql's \getenv), one per created
-- role: @@PASSWORD_ENV@@.
--
-- In ONE transaction:
--   1. the group roles (NOLOGIN) and every role whose status is not
--      `planned` (LOGIN, NOSUPERUSER, ..., CONNECTION LIMIT, password);
--   2. memberships: `observed` roles join the app role (they inherit all of
--      its privileges and have none of their own); `narrow` roles leave it;
--      each role joins its groups;
--   3. CONNECT and USAGE on schema public for every created role;
--   4. the groups' grants and each narrow role's grants, after revoking
--      everything else they hold in schema public. Objects that do not
--      exist yet are skipped (a new cluster's initdb run);
--   5. the row policies (db-grants.yaml `row_policies`): every policy named
--      ds_grants_* is dropped, then each listed one is created again as a
--      RESTRICTIVE policy for its role.

\set ON_ERROR_STOP on

@@PSQL_DEFAULTS@@

BEGIN;

-- Settings live only until COMMIT, so the passwords never outlast it.
SELECT
@@SETTINGS@@
\gset ignored_

-- 1. Roles.
DO $roles$
DECLARE
    app text := current_setting('ds_grants.app');
    r record;
    seen text[] := ARRAY[]::text[];
BEGIN
    IF NOT (SELECT rolsuper FROM pg_roles WHERE rolname = current_user) THEN
        RAISE EXCEPTION 'postgres-grants.sql must run as a superuser, not %',
            current_user;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = app) THEN
        RAISE EXCEPTION 'the app role % does not exist: run postgres-roles.sql first',
            app;
    END IF;
    FOR r IN
        SELECT v.kind, current_setting('ds_grants.' || v.kind) AS name
        FROM @@GROUP_ROWS@@
    LOOP
        IF r.name = app OR r.name = current_user OR r.name = ANY (seen) THEN
            RAISE EXCEPTION 'the % group name % must be a new, separate role',
                r.kind, r.name;
        END IF;
        seen := seen || r.name;
        IF EXISTS (SELECT 1 FROM pg_roles
                   WHERE rolname = r.name AND (rolsuper OR rolcanlogin)) THEN
            RAISE EXCEPTION 'refusing to turn % into a group (a superuser or a login role)',
                r.name;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r.name) THEN
            EXECUTE format('CREATE ROLE %I', r.name);
        END IF;
        EXECUTE format('ALTER ROLE %I WITH NOLOGIN NOSUPERUSER NOCREATEDB '
                       'NOCREATEROLE NOREPLICATION NOBYPASSRLS', r.name);
    END LOOP;
    FOR r IN
        SELECT v.kind, current_setting('ds_grants.' || v.kind) AS name,
               current_setting('ds_grants.' || v.kind || '_password') AS password,
               current_setting('ds_grants.' || v.kind || '_connection_limit')
                   AS connection_limit
        FROM @@ROLE_ROWS@@
    LOOP
        IF r.name = app OR r.name = current_user OR r.name = ANY (seen) THEN
            RAISE EXCEPTION 'the % role name % must be a new, separate role',
                r.kind, r.name;
        END IF;
        seen := seen || r.name;
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r.name AND rolsuper) THEN
            RAISE EXCEPTION 'refusing to demote existing superuser % (the % role)',
                r.name, r.kind;
        END IF;
        IF r.connection_limit !~ '^(-1|[0-9]+)$' THEN
            RAISE EXCEPTION 'the % role connection limit % is not a whole number',
                r.kind, r.connection_limit;
        END IF;
        IF r.password = '' THEN
            RAISE EXCEPTION 'no password for the % role: set DS_PG_%_PASSWORD',
                r.kind, upper(r.kind);
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r.name) THEN
            EXECUTE format('CREATE ROLE %I', r.name);
        END IF;
        EXECUTE format('ALTER ROLE %I WITH LOGIN NOSUPERUSER NOCREATEDB '
                       'NOCREATEROLE NOREPLICATION NOBYPASSRLS INHERIT '
                       'CONNECTION LIMIT %s', r.name, r.connection_limit);
        EXECUTE format('ALTER ROLE %I PASSWORD %L', r.name, r.password);
    END LOOP;
END
$roles$;

-- 2. Memberships, 3. CONNECT and USAGE.
DO $members$
DECLARE
    app text := current_setting('ds_grants.app');
    app_oid oid := (SELECT oid FROM pg_roles WHERE rolname = app);
    r record;
    member_oid oid;
BEGIN
    FOR r IN
        SELECT v.kind, v.status, current_setting('ds_grants.' || v.kind) AS name
        FROM @@ROLE_ROWS@@
    LOOP
        member_oid := (SELECT oid FROM pg_roles WHERE rolname = r.name);
        IF r.status = 'observed' AND NOT EXISTS (
            SELECT 1 FROM pg_auth_members
            WHERE roleid = app_oid AND member = member_oid) THEN
            EXECUTE format('GRANT %I TO %I', app, r.name);
        ELSIF r.status = 'narrow' AND EXISTS (
            SELECT 1 FROM pg_auth_members
            WHERE roleid = app_oid AND member = member_oid) THEN
            EXECUTE format('REVOKE %I FROM %I', app, r.name);
        END IF;
        EXECUTE format('GRANT CONNECT ON DATABASE %I TO %I',
                       current_database(), r.name);
        EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', r.name);
    END LOOP;
    FOR r IN
        SELECT current_setting('ds_grants.' || v.kind) AS member,
               current_setting('ds_grants.' || v.grp) AS grp
        FROM @@MEMBER_ROWS@@
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_auth_members
            WHERE roleid = (SELECT oid FROM pg_roles WHERE rolname = r.grp)
              AND member = (SELECT oid FROM pg_roles WHERE rolname = r.member)) THEN
            EXECUTE format('GRANT %I TO %I', r.grp, r.member);
        END IF;
    END LOOP;
END
$members$;

-- 4. Grants. Everything the groups and the created roles hold in schema
-- public is revoked first, so a grant removed from db-grants.yaml goes
-- away on the next run. Observed roles end with nothing of their own: they
-- use the app role's privileges.
DO $grants$
DECLARE
    r record;
    grantee text;
BEGIN
    FOR grantee IN
        SELECT current_setting('ds_grants.' || v.kind)
        FROM @@GRANTEE_ROWS@@
    LOOP
        EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I', grantee);
        EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %I', grantee);
        EXECUTE format('REVOKE ALL ON ALL ROUTINES IN SCHEMA public FROM %I', grantee);
    END LOOP;

    IF to_regclass('public._sqlx_migrations') IS NOT NULL THEN
        EXECUTE format('GRANT SELECT ON public._sqlx_migrations TO %I',
                       current_setting('ds_grants.schema_gate'));
    END IF;
    FOR r IN
        SELECT v.tbl
        FROM @@READ_SHARED_ROWS@@
        WHERE to_regclass(format('public.%I', v.tbl)) IS NOT NULL
    LOOP
        EXECUTE format('GRANT SELECT ON public.%I TO %I', r.tbl,
                       current_setting('ds_grants.read_shared'));
    END LOOP;

    -- Narrow roles: exactly their grants.
    FOR r IN
        SELECT v.tbl, current_setting('ds_grants.' || v.kind) AS grantee,
               v.priv, v.cols
        FROM @@TABLE_ROWS@@
        WHERE to_regclass(format('public.%I', v.tbl)) IS NOT NULL
    LOOP
        IF r.cols = '' THEN
            EXECUTE format('GRANT %s ON public.%I TO %I', r.priv, r.tbl, r.grantee);
        ELSE
            EXECUTE format('GRANT %s (%s) ON public.%I TO %I', r.priv,
                (SELECT string_agg(quote_ident(c), ', ')
                 FROM unnest(string_to_array(r.cols, ',')) AS c),
                r.tbl, r.grantee);
        END IF;
    END LOOP;
    FOR r IN
        SELECT v.seq, current_setting('ds_grants.' || v.kind) AS grantee
        FROM @@SEQUENCE_ROWS@@
        WHERE to_regclass(format('public.%I', v.seq)) IS NOT NULL
    LOOP
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE public.%I TO %I',
                       r.seq, r.grantee);
    END LOOP;
    FOR r IN
        SELECT v.sig, current_setting('ds_grants.' || v.kind) AS grantee
        FROM @@FUNCTION_ROWS@@
        WHERE to_regprocedure('public.' || v.sig) IS NOT NULL
    LOOP
        EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO %I',
                       to_regprocedure('public.' || r.sig), r.grantee);
    END LOOP;
END
$grants$;

-- 5. Row policies (spec §6.4, D10). Each is RESTRICTIVE, so it narrows its
-- role whatever permissive policy (the table's migration adds one for
-- PUBLIC) or membership (the app role) would otherwise let it see. It
-- takes effect once the table's migration has enabled row-level security.
DO $policies$
DECLARE
    r record;
BEGIN
    FOR r IN
        SELECT p.tablename, p.policyname
        FROM pg_policies p
        WHERE p.schemaname = 'public' AND p.policyname LIKE 'ds\_grants\_%'
    LOOP
        EXECUTE format('DROP POLICY %I ON public.%I', r.policyname, r.tablename);
    END LOOP;
    FOR r IN
        SELECT v.tbl, v.kind, current_setting('ds_grants.' || v.kind) AS grantee,
               v.cond
        FROM @@POLICY_ROWS@@
        WHERE to_regclass(format('public.%I', v.tbl)) IS NOT NULL
    LOOP
        EXECUTE format('CREATE POLICY %I ON public.%I AS RESTRICTIVE FOR ALL TO %I '
                       'USING (%s) WITH CHECK (%s)',
                       'ds_grants_' || r.kind, r.tbl, r.grantee, r.cond, r.cond);
    END LOOP;
END
$policies$;

COMMIT;
