#!/usr/bin/env python3
# ruff: noqa: T201  # a CLI that reports what it wrote (or found stale) on stdout
"""Generate the cargo-chef builder stages of the Rust service Dockerfiles.

  uv run scripts/gen-rust-dockerfiles.py          # rewrite docker/*.Dockerfile
  uv run scripts/gen-rust-dockerfiles.py --check  # exit 1 if any is stale

Every docker/<service>.Dockerfile builds one Rust service the same way, so
the part from `ARG CARGO_PROFILE` to the end of the `builder` stage is
generated from SERVICES below, between the BEGIN and END marker lines. The
rest of each file (its header comment and its runtime stage) is written by
hand and left alone. CI's scripts-lint job runs `--check` (through
scripts/lint-scripts.py), so an edit inside the markers, or a Dockerfile
with no SERVICES entry, fails CI.

Why generated: 18 copies of the same four stages, which must differ ONLY in
the `--bin` flags (see below), drift apart when edited by hand.

The stages (cargo-chef, https://github.com/LukeMathWalker/cargo-chef):

- chef: the Rust image, every service's build packages (the union, so this
  layer is identical, and built once, across all of them) and cargo-chef.
- planner: `cargo chef prepare` reduces the workspace to recipe.json, its
  manifests and lockfile. A source-only change leaves recipe.json unchanged.
- builder: `cargo chef cook` builds only the dependencies, from recipe.json,
  in their own layer; then the real source is copied in and `cargo build`
  compiles the workspace crates. A source-only change reuses the cook layer,
  locally and in CI (containers.yml imports it from the registry cache).

The cook MUST use exactly the final build's `--bin` flags, profile and
features, or its artifacts don't match and the build recompiles everything.
And it must never be one workspace-wide cook (or an all-binaries build):
Cargo unifies features across everything one invocation builds, which gives
rustls both its `ring` and `aws-lc-rs` providers, and then rustls cannot
pick a default provider at runtime (a TLS failure on the first connection).
One cargo call per service, with that service's own `--bin` flags, keeps
each binary's feature set what `cargo build --bin <service>` gives.

The final build RUN fails if it compiled anything but a workspace crate
(a `Compiling` line without an `(/app/...)` path): that means the cook no
longer matches the build and the cache is silently useless.
"""

import argparse
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCKER_DIR = ROOT / "docker"

BEGIN = "# BEGIN generated by scripts/gen-rust-dockerfiles.py; edit it, not this"
END = "# END generated by scripts/gen-rust-dockerfiles.py"

# The service (docker/<service>.Dockerfile) -> the binaries its image ships,
# the first being its ENTRYPOINT. Each is built with `--bin`; none needs a
# `-p` or `--features` today. Add those here (and to the template) if one
# ever does, for the cook and the build alike.
SERVICES: Mapping[str, Sequence[str]] = {
    "aggregator": ("aggregator",),
    "api": (
        "api",
        "backfill_trains",
        "backfill_incident_lines",
        "corpus_compare",
        "replay_uidless_movements",
        "backfill_line_train_summaries",
    ),
    "enricher": ("enricher",),
    "full-coverage-consumer": ("full-coverage-consumer",),
    "movement-relay": ("movement-relay",),
    "notifier": ("notifier",),
    "poller-incidents": ("poller-incidents",),
    "poller-irish-rail-gtfs": ("poller-irish-rail-gtfs",),
    "poller-irish-rail-live": ("poller-irish-rail-live",),
    "poller-ldbws": ("poller-ldbws",),
    "poller-nir-stations": ("poller-nir-stations",),
    "poller-stations": ("poller-stations",),
    "poller-tfl": ("poller-tfl",),
    "poller-tocs": ("poller-tocs",),
    "schedule-ingest": ("schedule-ingest",),
    "schedule-reference": ("schedule-reference",),
    "trust-backlog-consumer": ("trust-backlog-consumer",),
    "trust-consumer": ("trust-consumer",),
}

# Renovate bumps these in this file (renovate.json5's custom managers) on the
# same branch as the Dockerfiles' own FROM / `cargo install` lines, so its
# PRs stay drift-free; keep each assignment on one line for its regex.
# renovate: datasource=docker depName=rust
RUST_TAG = "1.88-bookworm"
RUST_DIGEST = "sha256:af306cfa71d987911a781c37b59d7d67d934f49684058f96cf72079c3626bfe0"
# renovate: datasource=crate depName=cargo-chef
CARGO_CHEF_VERSION = "0.1.78"
# Build-time packages, the union over every service: rdkafka's vendored
# librdkafka (movement-relay: cmake, libssl-dev, pkg-config, libsasl2-dev
# for sasl2-sys, libcurl4-openssl-dev for librdkafka's <curl/curl.h>) and
# web-push's OpenSSL (notifier: libssl-dev, pkg-config). Present for every
# service so the chef layer is shared; a crate that doesn't link them is
# unaffected (aws-lc-sys picks its cc builder whether or not cmake exists).
BUILD_PACKAGES = (
    "cmake",
    "libcurl4-openssl-dev",
    "libsasl2-dev",
    "libssl-dev",
    "pkg-config",
)

# The final build's check: print each `Compiling` line without an /app path
# (a dependency, not a workspace crate) and exit 1 if there was one.
CHECK_AWK = (
    "/^ +Compiling / && !/ \\(\\/app\\// { print; found = 1 } END { exit found }"
)
CHECK_ERROR = (
    "the build compiled the dependencies above; "
    "the cargo chef cook flags no longer match the build's"
)

CARGO_MOUNTS = (
    "RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry,"
    "sharing=locked \\\n"
    "    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git,"
    "sharing=locked \\\n"
)

TEMPLATE = """\
{begin}
# Builder stages: cargo-chef, so the dependency build is a layer of its own
# that a source-only change reuses (locally, and in CI from the registry
# build cache, see .github/workflows/containers.yml). The generator's
# docstring explains the stages and why the cook and the build must take
# exactly the same flags.
#
# CARGO_PROFILE picks the cargo build profile (and matching target/<profile>
# output dir): "release" (default) for optimized builds, "debug" for fast
# unoptimized dev builds. Set to "debug" by docker-compose.dev.yml, the
# override that `dev.env` selects via COMPOSE_FILE; docker-compose.yml on
# its own leaves it at "release".
ARG CARGO_PROFILE=release

FROM {image} AS chef

# The registry and git caches hold only downloaded sources, so every
# service shares them. `sharing=locked`: docker-compose builds in parallel.
# hadolint ignore=DL3008 # apt versions unpinned on purpose; see .hadolint.yaml
{mounts}    apt-get update \\
    && apt-get install -y --no-install-recommends {packages} \\
    && rm -rf /var/lib/apt/lists/* \\
    && cargo install cargo-chef --locked --version {chef_version}

WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
ARG CARGO_PROFILE

# No cache mount on target/: the cooked dependencies must land in this
# layer, which is what the next build (and CI's registry cache) reuses.
COPY --from=planner /app/recipe.json recipe.json
{mounts}    if [ "${{CARGO_PROFILE}}" = "release" ]; then \\
      cargo chef cook --release --locked --recipe-path recipe.json {bins}; \\
    else \\
      cargo chef cook --locked --recipe-path recipe.json {bins}; \\
    fi

COPY . .
# The same flags as the cook. cargo's log is printed after the build, then
# checked: a `Compiling` line without an /app path is a dependency the cook
# should have built, so the cook no longer matches and the build fails. The
# binaries are copied out and target/ is deleted in the same RUN, so this
# layer stays small in the build cache.
{mounts}    if [ "${{CARGO_PROFILE}}" = "release" ]; then \\
      cargo build --release --locked {bins} > /tmp/cargo-build.log 2>&1; \\
    else \\
      cargo build --locked {bins} > /tmp/cargo-build.log 2>&1; \\
    fi; \\
    status=$?; \\
    cat /tmp/cargo-build.log; \\
    if [ "${{status}}" -ne 0 ]; then exit "${{status}}"; fi; \\
    if ! awk '{check}' /tmp/cargo-build.log; then \\
      echo "error: {check_error}" >&2; \\
      exit 1; \\
    fi; \\
{copies}    && rm -rf /app/target /tmp/cargo-build.log
{end}
"""


def render(service: str) -> str:
    """Return the generated block for one service, markers included."""
    bins = SERVICES[service]
    copies = "".join(
        f'    {"&& " if i else ""}cp "/app/target/${{CARGO_PROFILE}}/{name}" '
        f"/usr/local/bin/{name} \\\n"
        for i, name in enumerate(bins)
    )
    return TEMPLATE.format(
        begin=BEGIN,
        end=END,
        image=f"rust:{RUST_TAG}@{RUST_DIGEST}",
        mounts=CARGO_MOUNTS,
        packages=" ".join(BUILD_PACKAGES),
        chef_version=CARGO_CHEF_VERSION,
        bins=" ".join(f"--bin {name}" for name in bins),
        copies=copies,
        check=CHECK_AWK,
        check_error=CHECK_ERROR,
    )


def splice(text: str, block: str, path: Path) -> str:
    """Replace the BEGIN..END block of a Dockerfile's text with `block`."""
    lines = text.splitlines(keepends=True)
    starts = [i for i, line in enumerate(lines) if line.rstrip("\n") == BEGIN]
    ends = [i for i, line in enumerate(lines) if line.rstrip("\n") == END]
    if len(starts) != 1 or len(ends) != 1 or ends[0] < starts[0]:
        msg = f"{path}: needs exactly one {BEGIN!r} line, then one {END!r} line"
        raise ValueError(msg)
    return "".join([*lines[: starts[0]], block, *lines[ends[0] + 1 :]])


def dockerfiles() -> dict[str, Path]:
    """Return the service Dockerfiles under docker/, by service name."""
    return {
        path.name.removesuffix(".Dockerfile"): path
        for path in sorted(DOCKER_DIR.glob("*.Dockerfile"))
    }


def main(argv: Sequence[str] | None = None) -> int:
    """Rewrite (or, with --check, verify) every service Dockerfile."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit 1 if any Dockerfile differs from its generated form",
    )
    args = parser.parse_args(argv)

    found = dockerfiles()
    problems = [
        f"docker/{name}.Dockerfile has no SERVICES entry in {Path(__file__).name}"
        for name in sorted(found.keys() - SERVICES.keys())
    ] + [
        f"SERVICES has {name!r} but docker/{name}.Dockerfile does not exist"
        for name in sorted(SERVICES.keys() - found.keys())
    ]
    stale: list[str] = []
    for name in sorted(found.keys() & SERVICES.keys()):
        path = found[name]
        text = path.read_text(encoding="utf-8")
        try:
            wanted = splice(text, render(name), path)
        except ValueError as error:
            problems.append(str(error))
            continue
        if wanted == text:
            continue
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.write_text(wanted, encoding="utf-8")

    for problem in problems:
        print(f"error: {problem}")
    if args.check:
        for path_name in stale:
            print(f"stale: {path_name}")
        if stale:
            print(f"run `uv run scripts/{Path(__file__).name}` to regenerate")
    else:
        for path_name in stale:
            print(f"wrote {path_name}")
    return 1 if problems or (args.check and stale) else 0


if __name__ == "__main__":
    sys.exit(main())
