-- GENERATED by scripts/gen-db-grants.py from db-grants.yaml (with the
-- template scripts/db-grants.sql.tpl). DO NOT EDIT: edit db-grants.yaml,
-- then run `uv run scripts/gen-db-grants.py render`.
--
-- Per-service Postgres roles (docs/postgres-app-role.md, Stage 0b; ingest
-- architecture spec §6). Idempotent. Run with psql as a SUPERUSER in the
-- application database, AFTER postgres-roles.sql (it needs the app role):
--
--   psql -X -d distant_signal -v app=distant_signal_app \
--     [-v <role>=<name>] [-v <role>_connection_limit=N] \
--     -f postgres-grants.sql
--
-- Passwords come from the environment (psql's \getenv), one per created
-- role: DS_PG_API_PASSWORD, DS_PG_AGGREGATOR_PASSWORD, DS_PG_ENRICHER_PASSWORD, DS_PG_NOTIFIER_PASSWORD, DS_PG_WRITER_PASSWORD, DS_PG_SCHEDULE_REFERENCE_PASSWORD, DS_PG_STATIONS_PASSWORD, DS_PG_INCIDENTS_PASSWORD, DS_PG_SCHEDULE_INGEST_PASSWORD, DS_PG_TRUST_BACKLOG_PASSWORD, DS_PG_TRUST_CONSUMER_PASSWORD, DS_PG_FULL_COVERAGE_RO_PASSWORD, DS_PG_LDBWS_RO_PASSWORD.
--
-- In ONE transaction:
--   1. the group roles (NOLOGIN) and every role whose status is not
--      `planned` (LOGIN, NOSUPERUSER, ..., CONNECTION LIMIT, password);
--   2. memberships: `observed` roles join the app role (they inherit all of
--      its privileges and have none of their own, but may not SET ROLE to
--      it: WITH INHERIT TRUE, SET FALSE, Postgres 16+); `narrow` roles leave it;
--      each role joins its groups (also SET FALSE);
--   3. CONNECT and USAGE on schema public for every created role;
--   4. the groups' grants and each narrow role's grants, after revoking
--      everything else they hold in schema public. Objects that do not
--      exist yet are skipped (a new cluster's initdb run);
--   5. the row policies (db-grants.yaml `row_policies`): every policy named
--      ds_grants_* is dropped, then each listed one is created again as a
--      RESTRICTIVE policy for its role (FOR ALL, or one per write command
--      for a `{writes: ...}` entry).

\set ON_ERROR_STOP on

-- No statement logging in this session (security review L8): the
-- passwords are literals in the set_config call below, so a failing
-- statement (log_min_error_statement), a slow one
-- (log_min_duration_statement) or log_statement = all would otherwise
-- write them to the server log.
SET log_min_error_statement = panic;
SET log_min_duration_statement = -1;
SET log_statement = none;

\if :{?app}
\else
\set app distant_signal_app
\endif
\if :{?read_shared}
\else
\set read_shared distant_signal_read_shared
\endif
\if :{?schema_gate}
\else
\set schema_gate distant_signal_schema_gate
\endif
\if :{?api}
\else
\set api distant_signal_api
\endif
\if :{?api_connection_limit}
\else
\set api_connection_limit 34
\endif
\if :{?aggregator}
\else
\set aggregator distant_signal_aggregator
\endif
\if :{?aggregator_connection_limit}
\else
\set aggregator_connection_limit 9
\endif
\if :{?enricher}
\else
\set enricher distant_signal_enricher
\endif
\if :{?enricher_connection_limit}
\else
\set enricher_connection_limit 4
\endif
\if :{?notifier}
\else
\set notifier distant_signal_notifier
\endif
\if :{?notifier_connection_limit}
\else
\set notifier_connection_limit 5
\endif
\if :{?writer}
\else
\set writer distant_signal_writer
\endif
\if :{?writer_connection_limit}
\else
\set writer_connection_limit 7
\endif
\if :{?schedule_reference}
\else
\set schedule_reference distant_signal_schedule_reference
\endif
\if :{?schedule_reference_connection_limit}
\else
\set schedule_reference_connection_limit 4
\endif
\if :{?stations}
\else
\set stations distant_signal_stations
\endif
\if :{?stations_connection_limit}
\else
\set stations_connection_limit 2
\endif
\if :{?incidents}
\else
\set incidents distant_signal_incidents
\endif
\if :{?incidents_connection_limit}
\else
\set incidents_connection_limit 3
\endif
\if :{?schedule_ingest}
\else
\set schedule_ingest distant_signal_schedule_ingest
\endif
\if :{?schedule_ingest_connection_limit}
\else
\set schedule_ingest_connection_limit 2
\endif
\if :{?trust_backlog}
\else
\set trust_backlog distant_signal_trust_backlog
\endif
\if :{?trust_backlog_connection_limit}
\else
\set trust_backlog_connection_limit 4
\endif
\if :{?trust_consumer}
\else
\set trust_consumer distant_signal_trust_consumer
\endif
\if :{?trust_consumer_connection_limit}
\else
\set trust_consumer_connection_limit 3
\endif
\if :{?full_coverage_ro}
\else
\set full_coverage_ro distant_signal_full_coverage_ro
\endif
\if :{?full_coverage_ro_connection_limit}
\else
\set full_coverage_ro_connection_limit 3
\endif
\if :{?ldbws_ro}
\else
\set ldbws_ro distant_signal_ldbws_ro
\endif
\if :{?ldbws_ro_connection_limit}
\else
\set ldbws_ro_connection_limit 2
\endif
\getenv api_password DS_PG_API_PASSWORD
\if :{?api_password}
\else
\set api_password ''
\endif
\getenv aggregator_password DS_PG_AGGREGATOR_PASSWORD
\if :{?aggregator_password}
\else
\set aggregator_password ''
\endif
\getenv enricher_password DS_PG_ENRICHER_PASSWORD
\if :{?enricher_password}
\else
\set enricher_password ''
\endif
\getenv notifier_password DS_PG_NOTIFIER_PASSWORD
\if :{?notifier_password}
\else
\set notifier_password ''
\endif
\getenv writer_password DS_PG_WRITER_PASSWORD
\if :{?writer_password}
\else
\set writer_password ''
\endif
\getenv schedule_reference_password DS_PG_SCHEDULE_REFERENCE_PASSWORD
\if :{?schedule_reference_password}
\else
\set schedule_reference_password ''
\endif
\getenv stations_password DS_PG_STATIONS_PASSWORD
\if :{?stations_password}
\else
\set stations_password ''
\endif
\getenv incidents_password DS_PG_INCIDENTS_PASSWORD
\if :{?incidents_password}
\else
\set incidents_password ''
\endif
\getenv schedule_ingest_password DS_PG_SCHEDULE_INGEST_PASSWORD
\if :{?schedule_ingest_password}
\else
\set schedule_ingest_password ''
\endif
\getenv trust_backlog_password DS_PG_TRUST_BACKLOG_PASSWORD
\if :{?trust_backlog_password}
\else
\set trust_backlog_password ''
\endif
\getenv trust_consumer_password DS_PG_TRUST_CONSUMER_PASSWORD
\if :{?trust_consumer_password}
\else
\set trust_consumer_password ''
\endif
\getenv full_coverage_ro_password DS_PG_FULL_COVERAGE_RO_PASSWORD
\if :{?full_coverage_ro_password}
\else
\set full_coverage_ro_password ''
\endif
\getenv ldbws_ro_password DS_PG_LDBWS_RO_PASSWORD
\if :{?ldbws_ro_password}
\else
\set ldbws_ro_password ''
\endif

BEGIN;

-- Settings live only until COMMIT, so the passwords never outlast it.
SELECT
    set_config('ds_grants.app', :'app', true),
    set_config('ds_grants.read_shared', :'read_shared', true),
    set_config('ds_grants.schema_gate', :'schema_gate', true),
    set_config('ds_grants.api', :'api', true),
    set_config('ds_grants.api_password', :'api_password', true),
    set_config('ds_grants.api_connection_limit', :'api_connection_limit', true),
    set_config('ds_grants.aggregator', :'aggregator', true),
    set_config('ds_grants.aggregator_password', :'aggregator_password', true),
    set_config('ds_grants.aggregator_connection_limit', :'aggregator_connection_limit', true),
    set_config('ds_grants.enricher', :'enricher', true),
    set_config('ds_grants.enricher_password', :'enricher_password', true),
    set_config('ds_grants.enricher_connection_limit', :'enricher_connection_limit', true),
    set_config('ds_grants.notifier', :'notifier', true),
    set_config('ds_grants.notifier_password', :'notifier_password', true),
    set_config('ds_grants.notifier_connection_limit', :'notifier_connection_limit', true),
    set_config('ds_grants.writer', :'writer', true),
    set_config('ds_grants.writer_password', :'writer_password', true),
    set_config('ds_grants.writer_connection_limit', :'writer_connection_limit', true),
    set_config('ds_grants.schedule_reference', :'schedule_reference', true),
    set_config('ds_grants.schedule_reference_password', :'schedule_reference_password', true),
    set_config('ds_grants.schedule_reference_connection_limit', :'schedule_reference_connection_limit', true),
    set_config('ds_grants.stations', :'stations', true),
    set_config('ds_grants.stations_password', :'stations_password', true),
    set_config('ds_grants.stations_connection_limit', :'stations_connection_limit', true),
    set_config('ds_grants.incidents', :'incidents', true),
    set_config('ds_grants.incidents_password', :'incidents_password', true),
    set_config('ds_grants.incidents_connection_limit', :'incidents_connection_limit', true),
    set_config('ds_grants.schedule_ingest', :'schedule_ingest', true),
    set_config('ds_grants.schedule_ingest_password', :'schedule_ingest_password', true),
    set_config('ds_grants.schedule_ingest_connection_limit', :'schedule_ingest_connection_limit', true),
    set_config('ds_grants.trust_backlog', :'trust_backlog', true),
    set_config('ds_grants.trust_backlog_password', :'trust_backlog_password', true),
    set_config('ds_grants.trust_backlog_connection_limit', :'trust_backlog_connection_limit', true),
    set_config('ds_grants.trust_consumer', :'trust_consumer', true),
    set_config('ds_grants.trust_consumer_password', :'trust_consumer_password', true),
    set_config('ds_grants.trust_consumer_connection_limit', :'trust_consumer_connection_limit', true),
    set_config('ds_grants.full_coverage_ro', :'full_coverage_ro', true),
    set_config('ds_grants.full_coverage_ro_password', :'full_coverage_ro_password', true),
    set_config('ds_grants.full_coverage_ro_connection_limit', :'full_coverage_ro_connection_limit', true),
    set_config('ds_grants.ldbws_ro', :'ldbws_ro', true),
    set_config('ds_grants.ldbws_ro_password', :'ldbws_ro_password', true),
    set_config('ds_grants.ldbws_ro_connection_limit', :'ldbws_ro_connection_limit', true)
\gset ignored_

-- 1. Roles.
DO $roles$
DECLARE
    app text := current_setting('ds_grants.app');
    r record;
    seen text[] := ARRAY[]::text[];
BEGIN
    IF NOT (SELECT rolsuper FROM pg_roles WHERE rolname = current_user) THEN
        RAISE EXCEPTION 'postgres-grants.sql must run as a superuser, not %',
            current_user;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = app) THEN
        RAISE EXCEPTION 'the app role % does not exist: run postgres-roles.sql first',
            app;
    END IF;
    FOR r IN
        SELECT v.kind, current_setting('ds_grants.' || v.kind) AS name
        FROM (VALUES
        ('read_shared'),
        ('schema_gate')) AS v(kind)
    LOOP
        IF r.name = app OR r.name = current_user OR r.name = ANY (seen) THEN
            RAISE EXCEPTION 'the % group name % must be a new, separate role',
                r.kind, r.name;
        END IF;
        seen := seen || r.name;
        IF EXISTS (SELECT 1 FROM pg_roles
                   WHERE rolname = r.name AND (rolsuper OR rolcanlogin)) THEN
            RAISE EXCEPTION 'refusing to turn % into a group (a superuser or a login role)',
                r.name;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r.name) THEN
            EXECUTE format('CREATE ROLE %I', r.name);
        END IF;
        EXECUTE format('ALTER ROLE %I WITH NOLOGIN NOSUPERUSER NOCREATEDB '
                       'NOCREATEROLE NOREPLICATION NOBYPASSRLS', r.name);
    END LOOP;
    FOR r IN
        SELECT v.kind, current_setting('ds_grants.' || v.kind) AS name,
               current_setting('ds_grants.' || v.kind || '_password') AS password,
               current_setting('ds_grants.' || v.kind || '_connection_limit')
                   AS connection_limit
        FROM (VALUES
        ('api', 'observed'),
        ('aggregator', 'observed'),
        ('enricher', 'observed'),
        ('notifier', 'observed'),
        ('writer', 'narrow'),
        ('schedule_reference', 'narrow'),
        ('stations', 'narrow'),
        ('incidents', 'narrow'),
        ('schedule_ingest', 'narrow'),
        ('trust_backlog', 'narrow'),
        ('trust_consumer', 'narrow'),
        ('full_coverage_ro', 'narrow'),
        ('ldbws_ro', 'narrow')) AS v(kind, status)
    LOOP
        IF r.name = app OR r.name = current_user OR r.name = ANY (seen) THEN
            RAISE EXCEPTION 'the % role name % must be a new, separate role',
                r.kind, r.name;
        END IF;
        seen := seen || r.name;
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r.name AND rolsuper) THEN
            RAISE EXCEPTION 'refusing to demote existing superuser % (the % role)',
                r.name, r.kind;
        END IF;
        IF r.connection_limit !~ '^(-1|[0-9]+)$' THEN
            RAISE EXCEPTION 'the % role connection limit % is not a whole number',
                r.kind, r.connection_limit;
        END IF;
        IF r.password = '' THEN
            RAISE EXCEPTION 'no password for the % role: set DS_PG_%_PASSWORD',
                r.kind, upper(r.kind);
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r.name) THEN
            EXECUTE format('CREATE ROLE %I', r.name);
        END IF;
        EXECUTE format('ALTER ROLE %I WITH LOGIN NOSUPERUSER NOCREATEDB '
                       'NOCREATEROLE NOREPLICATION NOBYPASSRLS INHERIT '
                       'CONNECTION LIMIT %s', r.name, r.connection_limit);
        EXECUTE format('ALTER ROLE %I PASSWORD %L', r.name, r.password);
    END LOOP;
END
$roles$;

-- 2. Memberships, 3. CONNECT and USAGE.
DO $members$
DECLARE
    app text := current_setting('ds_grants.app');
    app_oid oid := (SELECT oid FROM pg_roles WHERE rolname = app);
    r record;
    member_oid oid;
BEGIN
    FOR r IN
        SELECT v.kind, v.status, current_setting('ds_grants.' || v.kind) AS name
        FROM (VALUES
        ('api', 'observed'),
        ('aggregator', 'observed'),
        ('enricher', 'observed'),
        ('notifier', 'observed'),
        ('writer', 'narrow'),
        ('schedule_reference', 'narrow'),
        ('stations', 'narrow'),
        ('incidents', 'narrow'),
        ('schedule_ingest', 'narrow'),
        ('trust_backlog', 'narrow'),
        ('trust_consumer', 'narrow'),
        ('full_coverage_ro', 'narrow'),
        ('ldbws_ro', 'narrow')) AS v(kind, status)
    LOOP
        member_oid := (SELECT oid FROM pg_roles WHERE rolname = r.name);
        IF r.status = 'observed' THEN
            -- INHERIT TRUE: it uses the app role's privileges. SET FALSE
            -- (Postgres 16+): it cannot SET ROLE to the app role, which
            -- would shed the RESTRICTIVE row policies written for it
            -- (security review M1). Re-granting updates an existing
            -- membership's options.
            EXECUTE format('GRANT %I TO %I WITH INHERIT TRUE, SET FALSE',
                           app, r.name);
        ELSIF r.status = 'narrow' AND EXISTS (
            SELECT 1 FROM pg_auth_members
            WHERE roleid = app_oid AND member = member_oid) THEN
            EXECUTE format('REVOKE %I FROM %I', app, r.name);
        END IF;
        EXECUTE format('GRANT CONNECT ON DATABASE %I TO %I',
                       current_database(), r.name);
        EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', r.name);
    END LOOP;
    FOR r IN
        SELECT current_setting('ds_grants.' || v.kind) AS member,
               current_setting('ds_grants.' || v.grp) AS grp
        FROM (VALUES
        ('api', 'read_shared'),
        ('api', 'schema_gate'),
        ('aggregator', 'read_shared'),
        ('aggregator', 'schema_gate'),
        ('enricher', 'schema_gate'),
        ('notifier', 'read_shared'),
        ('notifier', 'schema_gate'),
        ('writer', 'read_shared'),
        ('writer', 'schema_gate'),
        ('schedule_reference', 'schema_gate'),
        ('stations', 'schema_gate'),
        ('incidents', 'schema_gate'),
        ('schedule_ingest', 'schema_gate'),
        ('trust_backlog', 'schema_gate'),
        ('trust_consumer', 'schema_gate'),
        ('full_coverage_ro', 'schema_gate'),
        ('ldbws_ro', 'schema_gate')) AS v(kind, grp)
    LOOP
        -- SET FALSE here too: a group's grants are only ever inherited.
        EXECUTE format('GRANT %I TO %I WITH INHERIT TRUE, SET FALSE',
                       r.grp, r.member);
    END LOOP;
END
$members$;

-- 4. Grants. Everything the groups and the created roles hold in schema
-- public is revoked first, so a grant removed from db-grants.yaml goes
-- away on the next run. Observed roles end with nothing of their own: they
-- use the app role's privileges.
DO $grants$
DECLARE
    r record;
    grantee text;
BEGIN
    FOR grantee IN
        SELECT current_setting('ds_grants.' || v.kind)
        FROM (VALUES
        ('read_shared'),
        ('schema_gate'),
        ('api'),
        ('aggregator'),
        ('enricher'),
        ('notifier'),
        ('writer'),
        ('schedule_reference'),
        ('stations'),
        ('incidents'),
        ('schedule_ingest'),
        ('trust_backlog'),
        ('trust_consumer'),
        ('full_coverage_ro'),
        ('ldbws_ro')) AS v(kind)
    LOOP
        EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I', grantee);
        EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %I', grantee);
        EXECUTE format('REVOKE ALL ON ALL ROUTINES IN SCHEMA public FROM %I', grantee);
    END LOOP;

    IF to_regclass('public._sqlx_migrations') IS NOT NULL THEN
        EXECUTE format('GRANT SELECT ON public._sqlx_migrations TO %I',
                       current_setting('ds_grants.schema_gate'));
    END IF;
    FOR r IN
        SELECT v.tbl
        FROM (VALUES
        ('trains'),
        ('train_movement_events'),
        ('train_current_state'),
        ('trust_event_backlog'),
        ('train_reasons'),
        ('notifier_forward_queue'),
        ('station_samples'),
        ('station_full_coverage_samples'),
        ('full_coverage_line_stats'),
        ('full_coverage_line_window_stats'),
        ('island_of_ireland_lines'),
        ('island_of_ireland_stations'),
        ('island_of_ireland_station_samples'),
        ('line_status'),
        ('line_status_history'),
        ('incidents'),
        ('incident_history'),
        ('incident_feed_state'),
        ('ingest_freshness'),
        ('line_status_daily_stats'),
        ('line_status_half_hourly_stats'),
        ('line_status_daily_coverage_stats'),
        ('line_status_half_hourly_coverage_stats'),
        ('full_coverage_window_verdicts'),
        ('corpus_crosswalk_build'),
        ('corpus_stanox_crs'),
        ('corpus_tiploc_crs'),
        ('stations'),
        ('tocs'),
        ('stanox_crs'),
        ('tiploc_crs'),
        ('fixed_links'),
        ('corpus_locations'),
        ('corpus_deliveries'),
        ('schedule_calling_points_full'),
        ('schedule_destination_departures'),
        ('schedule_network_departures'),
        ('schedule_line_population'),
        ('line_train_summaries'),
        ('schedule_services'),
        ('tiploc_locations'),
        ('schedule_reference_publishes'),
        ('schedule_feed_ingests')) AS v(tbl)
        WHERE to_regclass(format('public.%I', v.tbl)) IS NOT NULL
    LOOP
        EXECUTE format('GRANT SELECT ON public.%I TO %I', r.tbl,
                       current_setting('ds_grants.read_shared'));
    END LOOP;

    -- Narrow roles: exactly their grants.
    FOR r IN
        SELECT v.tbl, current_setting('ds_grants.' || v.kind) AS grantee,
               v.priv, v.cols
        FROM (VALUES
        ('trains', 'writer', 'SELECT', ''),
        ('trains', 'writer', 'INSERT', ''),
        ('trains', 'writer', 'UPDATE', ''),
        ('trains', 'trust_backlog', 'SELECT', ''),
        ('trains', 'trust_backlog', 'INSERT', ''),
        ('trains', 'trust_backlog', 'UPDATE', ''),
        ('train_subscriptions', 'writer', 'SELECT', 'id,trains_id,service_date,resolution_status,unresolved_from,pin_origin_crs,pin_scheduled_departure,pin_destination_crs,pin_skipped_stations,pin_platform,pin_planned_platform'),
        ('train_subscriptions', 'writer', 'UPDATE', 'resolution_status,unresolved_from,trains_id'),
        ('train_subscriptions', 'trust_backlog', 'SELECT', 'id,trains_id,resolution_status,unresolved_from'),
        ('train_subscriptions', 'trust_backlog', 'UPDATE', 'resolution_status,unresolved_from'),
        ('train_subscriptions', 'trust_consumer', 'SELECT', 'id,trains_id'),
        ('train_movement_events', 'writer', 'SELECT', ''),
        ('train_movement_events', 'writer', 'INSERT', ''),
        ('train_movement_events', 'trust_backlog', 'SELECT', ''),
        ('train_movement_events', 'trust_backlog', 'INSERT', ''),
        ('train_movement_events', 'trust_consumer', 'INSERT', ''),
        ('train_movement_events', 'trust_consumer', 'SELECT', 'trains_id,dedup_key'),
        ('train_current_state', 'writer', 'SELECT', ''),
        ('train_current_state', 'writer', 'INSERT', ''),
        ('train_current_state', 'writer', 'UPDATE', ''),
        ('train_current_state', 'trust_backlog', 'SELECT', ''),
        ('train_current_state', 'trust_backlog', 'INSERT', ''),
        ('train_current_state', 'trust_backlog', 'UPDATE', ''),
        ('train_current_state', 'trust_consumer', 'SELECT', ''),
        ('train_current_state', 'trust_consumer', 'INSERT', ''),
        ('train_current_state', 'trust_consumer', 'UPDATE', ''),
        ('trust_event_backlog', 'writer', 'SELECT', ''),
        ('trust_event_backlog', 'trust_backlog', 'SELECT', ''),
        ('trust_event_backlog', 'trust_backlog', 'INSERT', ''),
        ('train_reasons', 'trust_backlog', 'SELECT', ''),
        ('train_reasons', 'trust_backlog', 'INSERT', ''),
        ('train_reasons', 'trust_backlog', 'UPDATE', ''),
        ('notifier_forward_queue', 'writer', 'SELECT', ''),
        ('notifier_forward_queue', 'writer', 'INSERT', ''),
        ('notifier_forward_queue', 'trust_consumer', 'INSERT', ''),
        ('notifier_forward_queue', 'trust_consumer', 'SELECT', 'dedup_key'),
        ('train_event_outbox', 'trust_consumer', 'SELECT', ''),
        ('train_event_outbox', 'trust_consumer', 'INSERT', ''),
        ('train_event_outbox', 'writer', 'SELECT', ''),
        ('train_event_outbox', 'writer', 'UPDATE', ''),
        ('train_event_outbox', 'writer', 'DELETE', ''),
        ('ingest_dedup', 'writer', 'SELECT', ''),
        ('ingest_dedup', 'writer', 'INSERT', ''),
        ('ingest_dedup', 'writer', 'DELETE', ''),
        ('schedule_calling_points_full_publish_keys', 'schedule_reference', 'SELECT', ''),
        ('schedule_calling_points_full_publish_keys', 'schedule_reference', 'INSERT', ''),
        ('schedule_calling_points_full_publish_keys', 'schedule_reference', 'DELETE', ''),
        ('schedule_destination_departures_publish_keys', 'schedule_reference', 'SELECT', ''),
        ('schedule_destination_departures_publish_keys', 'schedule_reference', 'INSERT', ''),
        ('schedule_destination_departures_publish_keys', 'schedule_reference', 'DELETE', ''),
        ('station_samples', 'writer', 'SELECT', ''),
        ('station_samples', 'writer', 'INSERT', ''),
        ('station_samples', 'writer', 'UPDATE', ''),
        ('station_full_coverage_samples', 'writer', 'SELECT', ''),
        ('station_full_coverage_samples', 'writer', 'INSERT', ''),
        ('station_full_coverage_samples', 'writer', 'UPDATE', ''),
        ('full_coverage_line_stats', 'writer', 'SELECT', ''),
        ('full_coverage_line_stats', 'writer', 'INSERT', ''),
        ('full_coverage_line_stats', 'writer', 'UPDATE', ''),
        ('full_coverage_line_window_stats', 'writer', 'SELECT', ''),
        ('full_coverage_line_window_stats', 'writer', 'INSERT', ''),
        ('full_coverage_line_window_stats', 'writer', 'UPDATE', ''),
        ('island_of_ireland_lines', 'writer', 'SELECT', ''),
        ('island_of_ireland_lines', 'writer', 'INSERT', ''),
        ('island_of_ireland_lines', 'writer', 'UPDATE', ''),
        ('island_of_ireland_stations', 'writer', 'SELECT', ''),
        ('island_of_ireland_stations', 'writer', 'INSERT', ''),
        ('island_of_ireland_stations', 'writer', 'UPDATE', ''),
        ('island_of_ireland_station_samples', 'writer', 'SELECT', ''),
        ('island_of_ireland_station_samples', 'writer', 'INSERT', ''),
        ('island_of_ireland_station_samples', 'writer', 'UPDATE', ''),
        ('line_status', 'writer', 'SELECT', ''),
        ('line_status', 'writer', 'INSERT', ''),
        ('line_status', 'writer', 'UPDATE', ''),
        ('line_status', 'writer', 'DELETE', ''),
        ('line_status_history', 'writer', 'SELECT', ''),
        ('line_status_history', 'writer', 'INSERT', ''),
        ('incidents', 'incidents', 'SELECT', ''),
        ('incidents', 'incidents', 'INSERT', ''),
        ('incidents', 'incidents', 'UPDATE', ''),
        ('incident_history', 'incidents', 'SELECT', ''),
        ('incident_history', 'incidents', 'INSERT', ''),
        ('incident_feed_state', 'incidents', 'SELECT', ''),
        ('incident_feed_state', 'incidents', 'INSERT', ''),
        ('incident_feed_state', 'incidents', 'UPDATE', ''),
        ('ingest_freshness', 'writer', 'SELECT', ''),
        ('ingest_freshness', 'writer', 'INSERT', ''),
        ('ingest_freshness', 'writer', 'UPDATE', ''),
        ('ingest_freshness', 'stations', 'SELECT', ''),
        ('ingest_freshness', 'stations', 'INSERT', ''),
        ('ingest_freshness', 'stations', 'UPDATE', ''),
        ('ingest_freshness', 'incidents', 'SELECT', ''),
        ('ingest_freshness', 'incidents', 'INSERT', ''),
        ('ingest_freshness', 'incidents', 'UPDATE', ''),
        ('corpus_crosswalk_build', 'writer', 'SELECT', ''),
        ('corpus_crosswalk_build', 'writer', 'INSERT', ''),
        ('corpus_crosswalk_build', 'writer', 'UPDATE', ''),
        ('corpus_crosswalk_build', 'schedule_ingest', 'SELECT', ''),
        ('corpus_crosswalk_build', 'schedule_ingest', 'INSERT', ''),
        ('corpus_crosswalk_build', 'schedule_ingest', 'UPDATE', ''),
        ('corpus_stanox_crs', 'writer', 'SELECT', ''),
        ('corpus_stanox_crs', 'writer', 'INSERT', ''),
        ('corpus_stanox_crs', 'writer', 'DELETE', ''),
        ('corpus_stanox_crs', 'schedule_ingest', 'SELECT', ''),
        ('corpus_stanox_crs', 'schedule_ingest', 'INSERT', ''),
        ('corpus_stanox_crs', 'schedule_ingest', 'DELETE', ''),
        ('corpus_stanox_crs', 'trust_backlog', 'SELECT', ''),
        ('corpus_stanox_crs', 'full_coverage_ro', 'SELECT', ''),
        ('corpus_stanox_crs', 'trust_consumer', 'SELECT', ''),
        ('corpus_tiploc_crs', 'writer', 'SELECT', ''),
        ('corpus_tiploc_crs', 'writer', 'INSERT', ''),
        ('corpus_tiploc_crs', 'writer', 'DELETE', ''),
        ('corpus_tiploc_crs', 'schedule_ingest', 'SELECT', ''),
        ('corpus_tiploc_crs', 'schedule_ingest', 'INSERT', ''),
        ('corpus_tiploc_crs', 'schedule_ingest', 'DELETE', ''),
        ('corpus_tiploc_crs', 'schedule_reference', 'SELECT', ''),
        ('stations', 'writer', 'SELECT', ''),
        ('stations', 'stations', 'SELECT', ''),
        ('stations', 'stations', 'INSERT', ''),
        ('stations', 'stations', 'UPDATE', ''),
        ('stations', 'incidents', 'SELECT', ''),
        ('stations', 'schedule_ingest', 'SELECT', ''),
        ('tocs', 'writer', 'SELECT', ''),
        ('tocs', 'writer', 'INSERT', ''),
        ('tocs', 'writer', 'UPDATE', ''),
        ('stanox_crs', 'writer', 'SELECT', ''),
        ('stanox_crs', 'schedule_reference', 'SELECT', ''),
        ('stanox_crs', 'schedule_reference', 'INSERT', ''),
        ('stanox_crs', 'schedule_reference', 'UPDATE', ''),
        ('stanox_crs', 'schedule_reference', 'DELETE', ''),
        ('stanox_crs', 'trust_backlog', 'SELECT', ''),
        ('stanox_crs', 'trust_consumer', 'SELECT', ''),
        ('stanox_crs', 'full_coverage_ro', 'SELECT', ''),
        ('tiploc_crs', 'writer', 'SELECT', ''),
        ('tiploc_crs', 'schedule_reference', 'SELECT', ''),
        ('tiploc_crs', 'schedule_reference', 'INSERT', ''),
        ('tiploc_crs', 'schedule_reference', 'UPDATE', ''),
        ('tiploc_crs', 'schedule_reference', 'DELETE', ''),
        ('tiploc_crs', 'trust_backlog', 'SELECT', ''),
        ('tiploc_crs', 'full_coverage_ro', 'SELECT', ''),
        ('tiploc_crs', 'trust_consumer', 'SELECT', ''),
        ('fixed_links', 'writer', 'SELECT', ''),
        ('fixed_links', 'schedule_reference', 'SELECT', ''),
        ('fixed_links', 'schedule_reference', 'INSERT', ''),
        ('fixed_links', 'schedule_reference', 'UPDATE', ''),
        ('fixed_links', 'schedule_reference', 'DELETE', ''),
        ('corpus_locations', 'writer', 'SELECT', ''),
        ('corpus_locations', 'schedule_ingest', 'SELECT', ''),
        ('corpus_locations', 'schedule_ingest', 'INSERT', ''),
        ('corpus_locations', 'schedule_ingest', 'DELETE', ''),
        ('corpus_deliveries', 'writer', 'SELECT', ''),
        ('corpus_deliveries', 'schedule_ingest', 'SELECT', ''),
        ('corpus_deliveries', 'schedule_ingest', 'INSERT', ''),
        ('corpus_deliveries', 'schedule_ingest', 'UPDATE', ''),
        ('schedule_calling_points_full', 'schedule_reference', 'SELECT', ''),
        ('schedule_calling_points_full', 'schedule_reference', 'INSERT', ''),
        ('schedule_calling_points_full', 'schedule_reference', 'UPDATE', ''),
        ('schedule_calling_points_full', 'schedule_reference', 'DELETE', ''),
        ('schedule_destination_departures', 'schedule_reference', 'SELECT', ''),
        ('schedule_destination_departures', 'schedule_reference', 'INSERT', ''),
        ('schedule_destination_departures', 'schedule_reference', 'UPDATE', ''),
        ('schedule_destination_departures', 'schedule_reference', 'DELETE', ''),
        ('schedule_network_departures', 'schedule_reference', 'SELECT', ''),
        ('schedule_network_departures', 'schedule_reference', 'INSERT', ''),
        ('schedule_network_departures', 'schedule_reference', 'UPDATE', ''),
        ('schedule_network_departures', 'schedule_reference', 'DELETE', ''),
        ('schedule_line_population', 'schedule_reference', 'SELECT', ''),
        ('schedule_line_population', 'schedule_reference', 'INSERT', ''),
        ('schedule_line_population', 'schedule_reference', 'UPDATE', ''),
        ('schedule_line_population', 'schedule_reference', 'DELETE', ''),
        ('schedule_line_population', 'full_coverage_ro', 'SELECT', ''),
        ('line_train_summaries', 'schedule_reference', 'SELECT', ''),
        ('line_train_summaries', 'schedule_reference', 'INSERT', ''),
        ('line_train_summaries', 'schedule_reference', 'UPDATE', ''),
        ('line_train_summaries', 'schedule_reference', 'DELETE', ''),
        ('schedule_services', 'schedule_reference', 'SELECT', ''),
        ('schedule_services', 'schedule_reference', 'INSERT', ''),
        ('schedule_services', 'schedule_reference', 'UPDATE', ''),
        ('schedule_services', 'schedule_reference', 'DELETE', ''),
        ('tiploc_locations', 'schedule_reference', 'SELECT', ''),
        ('tiploc_locations', 'schedule_reference', 'INSERT', ''),
        ('tiploc_locations', 'schedule_reference', 'UPDATE', ''),
        ('tiploc_locations', 'schedule_reference', 'DELETE', ''),
        ('schedule_reference_publishes', 'schedule_reference', 'SELECT', ''),
        ('schedule_reference_publishes', 'schedule_reference', 'INSERT', ''),
        ('schedule_reference_publishes', 'schedule_reference', 'UPDATE', ''),
        ('schedule_feed_ingests', 'schedule_ingest', 'INSERT', ''),
        ('schedule_feed_ingests', 'schedule_ingest', 'SELECT', 'delivered_at'),
        ('ingest_active_tracked_trains', 'trust_consumer', 'SELECT', ''),
        ('ingest_sample_station_pins', 'ldbws_ro', 'SELECT', ''),
        ('ingest_custom_line_stations', 'ldbws_ro', 'SELECT', '')) AS v(tbl, kind, priv, cols)
        WHERE to_regclass(format('public.%I', v.tbl)) IS NOT NULL
    LOOP
        IF r.cols = '' THEN
            EXECUTE format('GRANT %s ON public.%I TO %I', r.priv, r.tbl, r.grantee);
        ELSE
            EXECUTE format('GRANT %s (%s) ON public.%I TO %I', r.priv,
                (SELECT string_agg(quote_ident(c), ', ')
                 FROM unnest(string_to_array(r.cols, ',')) AS c),
                r.tbl, r.grantee);
        END IF;
    END LOOP;
    FOR r IN
        SELECT v.seq, current_setting('ds_grants.' || v.kind) AS grantee
        FROM (VALUES
        ('trains_id_seq', 'writer'),
        ('trains_id_seq', 'trust_backlog'),
        ('train_movement_events_id_seq', 'writer'),
        ('train_movement_events_id_seq', 'trust_backlog'),
        ('train_movement_events_id_seq', 'trust_consumer'),
        ('train_current_state_id_seq', 'writer'),
        ('train_current_state_id_seq', 'trust_backlog'),
        ('train_current_state_id_seq', 'trust_consumer'),
        ('trust_event_backlog_id_seq', 'trust_backlog'),
        ('notifier_forward_queue_id_seq', 'writer'),
        ('notifier_forward_queue_id_seq', 'trust_consumer'),
        ('train_event_outbox_id_seq', 'trust_consumer'),
        ('line_status_history_id_seq', 'writer'),
        ('incident_history_id_seq', 'incidents'),
        ('fixed_links_id_seq', 'schedule_reference'),
        ('corpus_locations_id_seq', 'schedule_ingest')) AS v(seq, kind)
        WHERE to_regclass(format('public.%I', v.seq)) IS NOT NULL
    LOOP
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE public.%I TO %I',
                       r.seq, r.grantee);
    END LOOP;
    FOR r IN
        SELECT v.sig, current_setting('ds_grants.' || v.kind) AS grantee
        FROM (VALUES
        ('analyze_publish_keys(text)', 'schedule_reference')) AS v(sig, kind)
        WHERE to_regprocedure('public.' || v.sig) IS NOT NULL
    LOOP
        EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO %I',
                       to_regprocedure('public.' || r.sig), r.grantee);
    END LOOP;
END
$grants$;

-- 5. Row policies (spec §6.4, D10). Each is RESTRICTIVE, so it narrows its
-- role whatever permissive policy (the table's migration adds one for
-- PUBLIC) or membership (the app role) would otherwise let it see. It
-- takes effect once the table's migration has enabled row-level security.
DO $policies$
DECLARE
    r record;
BEGIN
    FOR r IN
        SELECT p.tablename, p.policyname
        FROM pg_policies p
        WHERE p.schemaname = 'public' AND p.policyname LIKE 'ds\_grants\_%'
    LOOP
        EXECUTE format('DROP POLICY %I ON public.%I', r.policyname, r.tablename);
    END LOOP;
    FOR r IN
        SELECT v.tbl, v.kind, v.cmd, current_setting('ds_grants.' || v.kind) AS grantee,
               v.cond
        FROM (VALUES
        ('line_status', 'writer', 'ALL', 'source = ''tfl'''),
        ('ingest_freshness', 'writer', 'INSERT', 'source IN (''tfl'', ''tocs'', ''station-samples'', ''full-coverage-stats'', ''full-coverage-window-stats'', ''station-full-coverage-samples'', ''island_of_ireland_stations_gtfs'', ''island_of_ireland_lines_gtfs'', ''island_of_ireland_stations_nir'', ''island_of_ireland_lines_nir'')'),
        ('ingest_freshness', 'writer', 'UPDATE', 'source IN (''tfl'', ''tocs'', ''station-samples'', ''full-coverage-stats'', ''full-coverage-window-stats'', ''station-full-coverage-samples'', ''island_of_ireland_stations_gtfs'', ''island_of_ireland_lines_gtfs'', ''island_of_ireland_stations_nir'', ''island_of_ireland_lines_nir'')'),
        ('ingest_freshness', 'writer', 'DELETE', 'source IN (''tfl'', ''tocs'', ''station-samples'', ''full-coverage-stats'', ''full-coverage-window-stats'', ''station-full-coverage-samples'', ''island_of_ireland_stations_gtfs'', ''island_of_ireland_lines_gtfs'', ''island_of_ireland_stations_nir'', ''island_of_ireland_lines_nir'')'),
        ('ingest_freshness', 'stations', 'INSERT', 'source = ''stations'''),
        ('ingest_freshness', 'stations', 'UPDATE', 'source = ''stations'''),
        ('ingest_freshness', 'stations', 'DELETE', 'source = ''stations'''),
        ('ingest_freshness', 'incidents', 'INSERT', 'source = ''incidents'''),
        ('ingest_freshness', 'incidents', 'UPDATE', 'source = ''incidents'''),
        ('ingest_freshness', 'incidents', 'DELETE', 'source = ''incidents''')) AS v(tbl, kind, cmd, cond)
        WHERE to_regclass(format('public.%I', v.tbl)) IS NOT NULL
    LOOP
        -- FOR ALL: ds_grants_<role>, USING and WITH CHECK. A writes-only
        -- entry: ds_grants_<role>_<command> for INSERT (WITH CHECK), UPDATE
        -- (both) and DELETE (USING); the role's reads stay unrestricted.
        EXECUTE format('CREATE POLICY %I ON public.%I AS RESTRICTIVE FOR %s TO %I %s',
                       'ds_grants_' || r.kind
                           || CASE WHEN r.cmd = 'ALL' THEN '' ELSE '_' || lower(r.cmd) END,
                       r.tbl, r.cmd, r.grantee,
                       CASE r.cmd
                           WHEN 'INSERT' THEN format('WITH CHECK (%s)', r.cond)
                           WHEN 'DELETE' THEN format('USING (%s)', r.cond)
                           ELSE format('USING (%s) WITH CHECK (%s)', r.cond, r.cond)
                       END);
    END LOOP;
END
$policies$;

COMMIT;
